export const CAREGIVER_QUOTES: string[] = [
  "Caregivers are the unsung heroes who show up every day with patience, compassion, and heart.",
  "Studies show that having consistent, trusted care improves recovery times by up to 30%.",
  "More than 53 million Americans provide unpaid care to a loved one each year.",
  "A good caregiver doesn't just assist — they bring dignity, warmth, and a sense of normalcy to everyday life.",
  "The bond between a caregiver and a family can last a lifetime — it starts with the right match.",
  "Professional caregivers undergo hundreds of hours of training to handle medical, emotional, and daily living needs.",
  "Families who use professional caregivers report significantly lower stress and better quality of life.",
  "Care is not just a service — it is a relationship built on trust, consistency, and compassion.",
  "The right caregiver can turn a difficult season of life into one filled with connection and comfort.",
  "Research shows that loneliness is as harmful to health as smoking 15 cigarettes a day — caregivers help combat that.",
  "Many caregivers describe their work as a calling, not just a career.",
  "Seniors who receive regular, personalized care are more likely to maintain independence longer.",
  "A caregiver's smile, presence, and patience can make all the difference in someone's day.",
  "Every family's care needs are unique — great matching means everyone thrives.",
  "Caregiving is one of the most meaningful professions: every shift, someone's life is made better.",
  "Over 70% of family members say professional care gave them peace of mind they didn't know they needed.",
  "The best caregivers listen first — they understand that the person they're caring for has a full life story.",
  "Home care allows loved ones to age in place, surrounded by familiar comforts and memories.",
  "Compassionate care reduces hospital readmissions and improves long-term health outcomes.",
  "Finding the right caregiver is one of the most important decisions a family can make — worth taking the time to get right.",
]
